"""Scan codebase and regenerate Phiversity_Obsidian.md with fresh [[wikilinks]]."""
import ast
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
WIKI_FILE = ROOT / "Phiversity_Obsidian.md"
SCAN_DIRS = ["scripts", "web", "test", "api", "alembic"]

IGNORE_DIRS = {"__pycache__", ".venv", ".venv311", ".ruff_cache", "media", "frontend_backup", "web_jobs", ".github", "_generated"}


def scan_modules(base: Path) -> list[dict]:
    modules = []
    for dirpath, dirnames, filenames in os.walk(base):
        rel = Path(dirpath).relative_to(ROOT)
        if any(p in IGNORE_DIRS for p in rel.parts):
            dirnames[:] = []
            continue
        for f in filenames:
            if not f.endswith(".py") or f.startswith("_"):
                continue
            fpath = Path(dirpath) / f
            rel_path = fpath.relative_to(ROOT)
            mod = {"path": str(rel_path).replace("\\", "/"), "classes": [], "funcs": [], "doc": ""}
            try:
                tree = ast.parse(fpath.read_text(encoding="utf-8"))
                mod["doc"] = ast.get_docstring(tree) or ""
                for node in ast.walk(tree):
                    if isinstance(node, ast.ClassDef):
                        mod["classes"].append(node.name)
                    elif isinstance(node, ast.FunctionDef):
                        mod["funcs"].append(node.name)
            except Exception:
                pass
            modules.append(mod)
    return modules


def build_moc(modules: list[dict]) -> str:
    # Group by top-level directory
    groups: dict[str, list[dict]] = {}
    for m in modules:
        top = m["path"].split("/")[0]
        groups.setdefault(top, []).append(m)

    lines = []
    lines.append("# Phiversity — Auto-generated Obsidian MOC")
    lines.append("")
    lines.append("> Regenerated by `scripts/generate_obsidian_moc.py`. Re-run anytime to refresh `[[wikilinks]]`.")
    lines.append("")

    for top in sorted(groups):
        lines.append(f"## `{top}/`")
        lines.append("")
        for m in sorted(groups[top], key=lambda x: x["path"]):
            label = m["path"].replace(".py", "")
            link = f"[[{m['path']}|{label}]]"
            doc_line = f" — {m['doc'].split(chr(10))[0]}" if m["doc"] else ""
            lines.append(f"- {link}{doc_line}")
            for cls in m["classes"][:5]:
                lines.append(f"  - `{cls}()`")
            for fn in m["funcs"][:5]:
                lines.append(f"  - `{fn}()`")
            if len(m["classes"]) > 5 or len(m["funcs"]) > 5:
                lines.append(f"  - *+{len(m['classes'])-5 if len(m['classes'])>5 else 0} classes, +{len(m['funcs'])-5 if len(m['funcs'])>5 else 0} funcs*")
            lines.append("")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("## Tags")
    lines.append("#pipeline #visualization #manim #tts #phiversity #obsidian")
    lines.append("")
    return "\n".join(lines)


def main():
    all_mods = []
    for d in SCAN_DIRS:
        p = ROOT / d
        if p.exists():
            all_mods.extend(scan_modules(p))

    content = build_moc(all_mods)
    WIKI_FILE.write_text(content, encoding="utf-8")
    print(f"[generate_obsidian_moc] Wrote {len(all_mods)} modules -> {WIKI_FILE}")


if __name__ == "__main__":
    main()
