import argparse
import json
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WEB = ROOT / "web"
DIST = ROOT / "dist"

TEMPLATE_CONFIG = """// Generated by package_web.py
window.APP_CONFIG = {{
  API_BASE: "{api_base}"
}};
"""

def copy_web(dist_dir: Path):
    dist_dir.mkdir(parents=True, exist_ok=True)
    for name in ["index.html", "app.js", "styles.css"]:
        src = WEB / name
        if src.exists():
            shutil.copy2(src, dist_dir / name)

def write_config(dist_dir: Path, api_base: str):
    (dist_dir / "config.js").write_text(TEMPLATE_CONFIG.format(api_base=api_base), encoding="utf-8")

def make_zip(dist_dir: Path, zip_name: str) -> Path:
    zip_path = ROOT / f"{zip_name}"
    if zip_path.suffix.lower() != ".zip":
        zip_path = zip_path.with_suffix(".zip")
    
    # shutil.make_archive wants base_name without extension
    base_name = str(zip_path.with_suffix(""))
    
    # Clear any previous tree used by make_archive
    if zip_path.exists():
        zip_path.unlink()
    
    shutil.make_archive(base_name, "zip", root_dir=str(dist_dir))
    return zip_path

def main():
    parser = argparse.ArgumentParser(description="Package web UI for Firebase Hosting")
    parser.add_argument("--api-base", default="", help="Absolute base URL for API server, e.g. https://your-domain.com")
    parser.add_argument("--out-dir", default=str(DIST), help="Output directory for packaged assets")
    parser.add_argument("--zip", dest="zip_name", default="firebase_upload.zip", help="Zip file name to create")
    args = parser.parse_args()

    dist_dir = Path(args.out_dir)
    if dist_dir.exists():
        shutil.rmtree(dist_dir)
    
    copy_web(dist_dir)
    write_config(dist_dir, args.api_base.rstrip("/"))
    z = make_zip(dist_dir, args.zip_name)
    
    print(f"Packaged web to: {dist_dir}")
    print(f"Created zip: {z}")
    print("\nNext steps:\n- Upload the zip to Firebase Hosting (Console -> Hosting -> Upload).\n- Set API_BASE to your server URL so the UI can reach /api.\n")

if __name__ == "__main__":
    main()
