from __future__ import annotations

from typing import Dict, List

PHYSICS_FEATURES: List[str] = [
    "free-body-auto-layout",
    "force-arrow-auto-scaling",
    "unit-consistency-badges",
    "sign-convention-overlay",
    "incline-component-splitter",
    "pulley-tension-color-coding",
    "radial-tangential-decomposition",
    "projectile-drag-toggle",
    "impulse-time-chart",
    "momentum-vector-stacking",
    "energy-bar-transitions",
    "work-area-shading",
    "power-flow-arrows",
    "static-kinetic-friction-switch",
    "rolling-constraint-visualizer",
    "shm-phase-wheel",
    "damped-envelope-display",
    "resonance-sweep-scene",
    "wave-superposition-animator",
    "node-antinode-labels",
    "doppler-geometry-helper",
    "lens-ray-module",
    "mirror-equation-widget",
    "refraction-angle-tracker",
    "electric-field-lines",
    "equipotential-contours",
    "circuit-current-animation",
    "kirchhoff-loop-highlighter",
    "rc-charging-timeline",
    "magnetic-force-direction-guide",
    "flux-change-induction-panel",
    "ac-phasor-animator",
    "transformer-ratio-scene",
    "pv-cycle-playback",
    "heat-gradient-coloring",
    "calorimetry-mixture-scene",
    "kinetic-theory-particles",
    "entropy-change-storyboard",
    "spacetime-diagram-mode",
    "twin-clock-dilation-scene",
    "gravity-field-map",
    "orbit-sandbox",
    "tidal-force-exaggerator",
    "rocket-equation-explainer",
    "buoyancy-force-balance",
    "streamline-fluid-view",
    "bernoulli-pressure-map",
    "velocity-profile-layers",
    "continuity-flow-tracer",
    "shock-front-marker",
    "stress-strain-plotter",
    "elastic-modulus-fit",
    "beam-deflection-scene",
    "torque-arm-visualizer",
    "angular-momentum-keeper",
    "gyro-precession-animation",
    "pseudoforce-overlays",
    "coriolis-trajectory-demo",
    "chaotic-pendulum-compare",
    "numerical-convergence-plot",
    "error-propagation-panel",
    "significant-figure-checker",
    "dimensional-analysis-hints",
    "boundary-condition-callouts",
    "initial-condition-cards",
    "experiment-setup-framing",
    "uncertainty-whiskers",
    "residual-fit-subplot",
    "log-axis-toggle",
    "constants-quick-panel",
    "derivation-breadcrumbs",
    "assumption-checklist",
    "mistake-branch-scenes",
    "sanity-check-prompts",
    "plausibility-meter",
    "multi-method-compare",
    "unit-converter-inline",
    "context-sensitive-narration",
    "exam-timer-overlay",
    "what-if-sliders",
    "random-parameter-generator",
    "auto-practice-variants",
    "difficulty-adaptive-pacing",
    "duration-optimizer",
    "voiceover-sync-highlights",
    "high-contrast-theme",
    "color-blind-palette",
    "equation-read-aloud-cues",
    "multilingual-symbol-glossary",
    "learning-checkpoints",
    "progressive-hint-reveal",
    "mastery-score-tracker",
    "teacher-annotation-layer",
    "student-pause-points",
    "scene-metadata-export",
    "snapshot-regression-tests",
    "visual-diff-testing",
    "render-quality-auto-presets",
    "mobile-safe-layout-mode",
    "worksheet-export-pack",
]

MATHEMATICS_FEATURES: List[str] = [
    "algebraic-transformation-tracker",
    "equation-balancing-animator",
    "step-validity-checker",
    "domain-restriction-alerts",
    "function-behavior-summary-cards",
    "intercept-auto-markers",
    "asymptote-detectors",
    "monotonicity-arrows",
    "concavity-shading",
    "inflection-point-labels",
    "tangent-secant-comparison",
    "derivative-meaning-scene",
    "integral-area-fill",
    "riemann-sum-builder",
    "ftc-linking-visual",
    "series-partial-sum-animator",
    "convergence-diagnostics",
    "limit-epsilon-delta-sketch",
    "lhospital-trigger-hints",
    "implicit-differentiation-flow",
    "optimization-constraint-panel",
    "critical-point-sorter",
    "newton-method-iteration-trail",
    "root-bracketing-visualizer",
    "matrix-row-operation-playback",
    "determinant-geometric-meaning",
    "eigenvector-direction-scene",
    "eigenvalue-scaling-animation",
    "diagonalization-checker",
    "linear-transform-grid-warp",
    "vector-space-basis-visuals",
    "orthogonality-projector",
    "gram-schmidt-animation",
    "least-squares-residual-bars",
    "probability-tree-builder",
    "bayes-update-animation",
    "distribution-shape-library",
    "pmf-cdf-linked-view",
    "z-score-conversion-panel",
    "confidence-interval-strip",
    "hypothesis-test-flowchart",
    "p-value-intuition-scene",
    "regression-line-fitting",
    "correlation-caveat-warnings",
    "combinatorics-counting-trees",
    "permutation-combination-toggles",
    "number-line-inequality-shading",
    "absolute-value-case-splitter",
    "piecewise-function-animator",
    "complex-plane-operations",
    "polar-rectangular-conversion",
    "argand-rotation-animation",
    "de-moivre-visualizer",
    "differential-equation-slope-fields",
    "phase-portrait-generator",
    "separation-of-variables-guide",
    "laplace-transform-map",
    "fourier-term-buildup",
    "pde-boundary-animation",
    "geometry-construction-helper",
    "triangle-theorem-overlays",
    "circle-theorem-overlays",
    "coordinate-geometry-scene",
    "conic-section-morphing",
    "area-volume-decomposition",
    "three-d-surface-slicer",
    "parametric-curve-animator",
    "vector-calculus-operators",
    "gradient-divergence-curl-scene",
    "jacobian-distortion-map",
    "symbolic-to-numeric-bridge",
    "units-in-math-optional-mode",
    "notation-consistency-checks",
    "common-error-prompts",
    "alternate-solution-comparer",
    "proof-skeleton-templates",
    "contradiction-proof-flow",
    "induction-visual-ladder",
    "graph-theory-explorers",
    "shortest-path-animation",
    "network-flow-scene",
    "modular-arithmetic-clocks",
    "cryptography-mini-visuals",
    "recurrence-relation-unfolding",
    "generating-function-hints",
    "ode-pde-solver-chooser",
    "difficulty-adaptive-hints",
    "exam-style-checkpoints",
    "memory-recall-flash-scenes",
    "quick-recap-scenes",
    "formula-sheet-auto-build",
    "practice-set-auto-generate",
    "skill-gap-targeting",
    "mastery-heatmap",
    "teacher-feedback-anchors",
    "rubric-aligned-outputs",
    "visual-accessibility-themes",
    "language-localization-symbols",
    "mobile-equation-layout",
    "interactive-challenge-mode",
]

CHEMISTRY_FEATURES: List[str] = [
    "mole-concept-bead-model",
    "stoichiometry-ratio-rails",
    "limiting-reagent-detector",
    "percent-yield-calculator-scene",
    "titration-setup-visual",
    "indicator-color-transition",
    "ph-scale-dynamic-pointer",
    "buffer-region-explanation",
    "henderson-hasselbalch-helper",
    "acid-base-strength-ranking",
    "ka-kb-relation-panel",
    "solubility-curve-viewer",
    "ksp-precipitation-trigger",
    "common-ion-effect-demo",
    "reaction-quotient-tracker",
    "equilibrium-shift-animator",
    "le-chatelier-controls",
    "ice-table-storyboard",
    "rate-law-extraction-scene",
    "order-determination-chart",
    "arrhenius-plot-visual",
    "catalyst-pathway-comparison",
    "energy-profile-diagram",
    "activation-energy-highlight",
    "thermochemistry-sign-check",
    "hess-law-pathway-map",
    "bond-enthalpy-estimator",
    "calorimeter-setup-scene",
    "phase-diagram-navigator",
    "heating-curve-segments",
    "vapor-pressure-relation",
    "gas-law-process-paths",
    "ideal-vs-real-gas-compare",
    "kinetic-molecular-animation",
    "diffusion-effusion-scene",
    "hybridization-geometry-viewer",
    "vsepr-shape-builder",
    "orbital-overlap-visuals",
    "molecular-polarity-arrows",
    "intermolecular-force-ranking",
    "crystal-lattice-types",
    "unit-cell-visualization",
    "oxidation-number-tracker",
    "redox-half-reaction-balancer",
    "electrochemical-cell-animator",
    "nernst-equation-panel",
    "galvanic-electrolytic-compare",
    "salt-bridge-ion-flow",
    "conductivity-trend-chart",
    "solvation-shell-animation",
    "concentration-unit-converter",
    "molarity-molality-chooser",
    "dilution-equation-guide",
    "spectroscopy-peak-labels",
    "ir-functional-group-hints",
    "nmr-splitting-visual",
    "uv-vis-absorbance-scene",
    "beer-lambert-linearity",
    "chromatography-separation-animation",
    "distillation-setup-visual",
    "extraction-partition-scene",
    "organic-mechanism-arrows",
    "sn1-sn2-pathway-compare",
    "e1-e2-condition-map",
    "aromatic-substitution-guide",
    "carbonyl-reaction-pathways",
    "polymerization-sequence-scene",
    "biochemistry-pathway-snapshots",
    "enzyme-kinetics-graph",
    "michaelis-menten-visual",
    "lab-safety-icon-overlay",
    "ppe-checklist-panel",
    "waste-disposal-prompts",
    "significant-figure-chemistry-mode",
    "balanced-equation-validator",
    "state-symbol-validator",
    "aqueous-solid-gas-color-coding",
    "concentration-time-profiles",
    "reaction-progress-coordinate",
    "common-misconception-alerts",
    "error-source-callouts",
    "data-table-auto-graph",
    "lab-report-template-scene",
    "practical-exam-mode",
    "multi-step-synthesis-planner",
    "reagent-compatibility-checker",
    "green-chemistry-score",
    "industrial-process-case-studies",
    "environmental-chemistry-overlays",
    "atmospheric-chemistry-scenes",
    "water-treatment-process-visuals",
    "material-chemistry-modules",
    "battery-chemistry-explainer",
    "corrosion-mechanism-scene",
    "nanochemistry-visual-intro",
    "adaptive-difficulty-prompts",
    "practice-question-generator",
    "mastery-diagnostics",
    "mobile-safe-glassware-layout",
    "voiceover-safe-naming-mode",
]

ECONOMICS_FEATURES: List[str] = [
    "supply-demand-auto-graph",
    "equilibrium-intersection-marker",
    "shift-vs-movement-detector",
    "tax-wedge-visualizer",
    "subsidy-effect-overlay",
    "price-ceiling-shortage-scene",
    "price-floor-surplus-scene",
    "consumer-surplus-shading",
    "producer-surplus-shading",
    "deadweight-loss-region",
    "elasticity-arc-calculator",
    "point-elasticity-marker",
    "cross-elasticity-mapping",
    "income-elasticity-mapping",
    "revenue-test-animator",
    "cost-curves-bundle",
    "mc-equals-mr-optimizer",
    "perfect-competition-module",
    "monopoly-pricing-visual",
    "monopolistic-competition-compare",
    "oligopoly-payoff-matrix",
    "game-theory-tree-scene",
    "nash-equilibrium-finder",
    "prisoners-dilemma-simulator",
    "externality-welfare-diagram",
    "pigouvian-tax-scene",
    "public-goods-free-rider-demo",
    "tragedy-of-commons-visual",
    "production-possibility-frontier",
    "opportunity-cost-animation",
    "comparative-advantage-table",
    "trade-gains-breakdown",
    "tariff-incidence-scene",
    "quota-welfare-effects",
    "exchange-rate-graph",
    "forex-shock-visual",
    "balance-of-payments-flow",
    "gdp-component-stack",
    "real-vs-nominal-gdp",
    "gdp-deflator-explanation",
    "cpi-basket-animation",
    "inflation-decomposition",
    "unemployment-types-module",
    "phillips-curve-context",
    "ad-as-framework-scene",
    "fiscal-policy-shift-visual",
    "multiplier-process-storyboard",
    "monetary-policy-transmission",
    "is-lm-simplified-visual",
    "liquidity-trap-case",
    "interest-rate-corridor-panel",
    "yield-curve-interpretation",
    "banking-reserve-cycle",
    "credit-creation-animation",
    "business-cycle-phase-map",
    "output-gap-indicator",
    "stabilizer-policy-module",
    "debt-dynamics-chart",
    "laffer-curve-caveats",
    "tax-incidence-by-elasticity",
    "lorenz-curve-builder",
    "gini-coefficient-visual",
    "poverty-trap-scene",
    "human-capital-growth-model",
    "solow-growth-intuition",
    "productivity-decomposition",
    "network-effects-economics",
    "platform-market-diagrams",
    "auction-mechanism-visual",
    "adverse-selection-scene",
    "moral-hazard-scene",
    "principal-agent-framework",
    "information-asymmetry-overlays",
    "behavioral-bias-callouts",
    "nudge-policy-visuals",
    "prospect-theory-sketch",
    "time-preference-discounting",
    "intertemporal-choice-scene",
    "environmental-economics-panel",
    "carbon-pricing-comparison",
    "cap-and-trade-simulator",
    "cost-benefit-timeline",
    "development-indicators-dashboard",
    "ppp-adjustment-visual",
    "labor-market-matching-scene",
    "wage-floor-effects",
    "migration-and-labor-shifts",
    "housing-market-dynamics",
    "real-estate-bubble-indicators",
    "financial-contagion-network",
    "risk-return-frontier-scene",
    "diversification-visual",
    "portfolio-rebalancing-demo",
    "policy-tradeoff-matrix",
    "scenario-sensitivity-sliders",
    "data-source-annotation-layer",
    "historical-event-overlays",
    "exam-graph-practice-mode",
    "adaptive-question-generator",
    "policy-memo-auto-summary",
    "marginal-utility-schedule-builder",
    "indifference-curve-map",
    "budget-constraint-pivot",
    "revealed-preference-checker",
    "engel-curve-visualizer",
    "hicksian-vs-marshallian-demand",
    "substitution-income-effect-split",
    "slutsky-decomposition-panel",
    "edgeworth-box-interaction",
    "contract-curve-tracer",
    "utility-maximization-stepper",
    "expenditure-minimization-stepper",
    "production-function-surface",
    "isoquant-isocost-tangent",
    "returns-to-scale-explorer",
    "cobb-douglas-parameter-slider",
    "translog-cost-visual",
    "total-product-average-product-map",
    "learning-curve-cost-drop",
    "capacity-utilization-gauge",
    "shutdown-condition-flagger",
    "breakeven-point-annotator",
    "long-run-entry-exit-simulator",
    "kinked-demand-curve-scene",
    "stackelberg-leader-follower-sim",
    "bertrand-price-war-simulator",
    "cournot-reaction-curves",
    "herfindahl-index-calculator",
    "contestable-market-checker",
    "two-part-tariff-visualizer",
    "price-discrimination-degree-comparator",
    "bundle-pricing-profit-map",
    "tie-in-sales-welfare-panel",
    "vertical-restraint-effects",
    "merger-synergy-vs-market-power",
    "antitrust-screening-dashboard",
    "consumer-search-cost-model",
    "menu-cost-inflation-channel",
    "efficiency-wage-unemployment-scene",
    "insider-outsider-labor-model",
    "monopsony-wage-setting-visual",
    "bargaining-theory-wage-band",
    "labor-supply-leisure-tradeoff",
    "reservation-wage-threshold",
    "gig-economy-matching-dynamics",
    "minimum-income-policy-compare",
    "universal-basic-income-simulator",
    "tax-benefit-cliff-detector",
    "social-insurance-pooling-scene",
    "pension-sustainability-path",
    "demographic-dividend-model",
    "dependency-ratio-forecast",
    "savings-investment-gap-monitor",
    "current-account-sustainability",
    "sovereign-risk-spread-tracker",
    "debt-restructuring-scenario-tree",
    "capital-flight-early-warning",
    "currency-crisis-first-second-gen",
    "impossible-trinity-triangle",
    "sterilized-intervention-effects",
    "taylor-rule-policy-plot",
    "forward-guidance-channel-map",
    "quantitative-easing-balance-sheet",
    "money-demand-liquidity-preference",
    "credit-spread-transmission",
    "shadow-banking-flow-map",
    "macroprudential-toolkit-simulator",
    "stress-test-scenario-engine",
    "bank-run-coordination-game",
    "deposit-insurance-moral-hazard",
    "payment-system-liquidity-grid",
    "fintech-adoption-s-curve",
    "digital-currency-policy-panel",
    "remittance-flow-development-link",
    "trade-gravity-model-visual",
    "global-value-chain-mapper",
    "terms-of-trade-shock-panel",
    "import-substitution-vs-export-led",
    "infant-industry-protection-check",
    "strategic-trade-policy-case",
    "sanctions-supply-chain-impact",
    "commodity-cycle-vulnerability",
    "dutch-disease-diagnostics",
    "resource-curse-governance-links",
    "fiscal-federalism-transfer-map",
    "public-choice-incentive-diagram",
    "median-voter-policy-outcome",
    "voting-paradox-illustrator",
    "mechanism-design-incentive-compatibility",
    "matching-market-stable-marriage",
    "school-choice-allocation-sim",
    "health-economics-insurance-selection",
    "pharmaceutical-pricing-access-tradeoff",
    "patent-policy-innovation-balance",
    "climate-damage-function-viewer",
    "integrated-assessment-model-snapshot",
    "resilience-investment-cost-curve",
    "disaster-risk-insurance-pool",
    "informal-economy-measurement-panel",
    "satellite-data-economic-nowcast",
]

SUBJECT_FEATURES: Dict[str, List[str]] = {
    "physics": PHYSICS_FEATURES,
    "mathematics": MATHEMATICS_FEATURES,
    "chemistry": CHEMISTRY_FEATURES,
    "economics": ECONOMICS_FEATURES,
}


def total_feature_count() -> int:
    return sum(len(v) for v in SUBJECT_FEATURES.values())


def get_subject_features(subject: str) -> List[str]:
    return list(SUBJECT_FEATURES.get((subject or "").strip().lower(), []))


def build_subject_feature_directive(subject: str, mode: str | None = None, max_items: int = 24) -> str:
    s = (subject or "").strip().lower()
    features = get_subject_features(s)
    if not features:
        return ""

    m = (mode or "question_solving").strip().lower()
    if m == "lecture":
        selected = features[:max_items]
    elif m == "revision":
        selected = features[-max_items:]
    else:
        step = max(1, len(features) // max_items)
        selected = features[::step][:max_items]

    selected_str = "\n".join(f"- {name}" for name in selected)
    return (
        f"SUBJECT FEATURE PACK ({s.upper()}): {len(features)} available features from the global {total_feature_count()}-feature catalog.\n"
        "Prioritize these capabilities while generating solution and animation plan:\n"
        f"{selected_str}\n"
        "Keep scenes tightly tied to the user question while using these features where relevant."
    )


# Contract checks: enforce base subject counts and expanded economics inventory.
if len(PHYSICS_FEATURES) != 100:
    raise RuntimeError(f"Physics feature catalog must have 100 items, got {len(PHYSICS_FEATURES)}")
if len(MATHEMATICS_FEATURES) != 100:
    raise RuntimeError(f"Mathematics feature catalog must have 100 items, got {len(MATHEMATICS_FEATURES)}")
if len(CHEMISTRY_FEATURES) != 100:
    raise RuntimeError(f"Chemistry feature catalog must have 100 items, got {len(CHEMISTRY_FEATURES)}")
if len(ECONOMICS_FEATURES) != 200:
    raise RuntimeError(f"Economics feature catalog must have 200 items, got {len(ECONOMICS_FEATURES)}")
if len(set(ECONOMICS_FEATURES)) != len(ECONOMICS_FEATURES):
    raise RuntimeError("Economics feature catalog contains duplicate items")
if total_feature_count() != 500:
    raise RuntimeError(f"Global feature catalog must have 500 items, got {total_feature_count()}")
